---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-15.10
    driver:
      box: ubuntu/wily64

suites:
  - name: node
    driver:
      network:
      - ["private_network", {ip: "192.168.40.11"}]
    run_list:
      - recipe[kubernetes-cluster::node]
  - name: master
    driver:
      network:
      - ["private_network", {ip: "192.168.40.10"}]
    run_list:
      - recipe[kubernetes-cluster::master]
