name             'kubernetes-install'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kubernetes-install'
long_description 'Installs/Configures kubernetes-install'
version          '0.1.0'
