#!/bin/bash
git fetch --tags
pwd=`git rev-parse --show-toplevel`
release=`git describe --abbrev=0 --tags`
version=`echo $release | awk -F \. '{ print $1 }'`
mayor=`echo $release | awk -F \. '{ print $2 }'`
minor=`echo $release | awk -F \. '{ print $3 }'`
new_minor=$(( $minor + 1 ))
echo "$version.$mayor.$new_minor" >> $PWD/VERSION
git add VERSION
git tag $new_release

